
name: Java MODOLO

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  PROJETO_JAVA_Nativo:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Instalando a JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Compilar o JAVA
      run: |
        cd src
        javac -cp . Main.java

    - name: Executando o Projeto
      run: |
        cd src
        java Main 

    - name: Install PostgreSQL JDBC driver
      run: |
        mkdir -p lib
        wget https://jdbc.postgresql.org/download/postgresql-42.3.1.jar -O lib/postgresql.jar
